version: '3.8'
services:
  auth_app:
    build: 
      context: .
    container_name: auth_container
    image: django_auth_image:django_auth_tg
    command: sh -c "sleep 15 && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./g_auth:/app_auth
    ports:
      - "8000:8080"

  postgres_app:
    image: postgres
    container_name: postgres_container
    environment:
      - POSTGRES_DB=auth_app_database
      - POSTGRES_USER=palash
      - POSTGRES_PASSWORD=B1234567
    volumes:
      - ./postgres_db/db:/var/lib/postgresql/data

    